### ISSUE TITLE
This action can't auto upload to Artifact

### ISSUE THREAD

**Issue by wherewhere** [TheDoctor0/zip-release#10]
This action can't auto upload to Artifact. We can use Upload-Artifact to upload the zip. But it is not convenient. Hope author can add this feature.
My code:
```
name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        type: 'zip'
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./release.zip
```
