### ISSUE TITLE
Excluding a folder, all its files and subfolders

### ISSUE THREAD

**Issue by TheFlyingBadger** [TheDoctor0/zip-release#15]
I'm having a bit of bother trying to exclude a folder (in my example called "folder")

in my repo TheFlyingBadger/test i've got an exclusion of

```yaml
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.4.2
        with:
                filename: ${{ needs.checktag.outputs.zipname }}
                exclusions: '*.git* ./folder*'
```
[Action](https://github.com/TheFlyingBadger/test/blob/main/.github/workflows/blank.yml)

but, even with various combos of slashes and asters, i'm still getting variously the empty folder (which isn't the *end* of the world) or the folder with it's dummy files in.

pointers for my stupidity?
