### ISSUE TITLE
Windows environment

### ISSUE THREAD

**Issue by marceltaeumel** [TheDoctor0/zip-release#17]
This action does not seem to work in a Windows environment:
```
sh: D:a_actionsthedoctor0zip-releasemaster/entrypoint.sh: No such file or directory
```

https://github.com/marceltaeumel/opensmalltalk-vm/runs/3136118562?check_suite_focus=true
```
      - name: Pack VM
        uses: thedoctor0/zip-release@master
        with:
          path: 'products/vm'
          filename: 'products/${{ env.IDENTIFIER }}_${{ env.REVISION }}.zip'
          exclusions: '*.def *.exp *.lib *.map *.o *.res *Unstripped* *.ignore'
```

https://github.com/marceltaeumel/opensmalltalk-vm/runs/3135986712?check_suite_focus=true
```
      - name: Pack VM
        uses: thedoctor0/zip-release@master
        with:
          directory: '${{ env.PRODUCTS_PATH }}/vm'
          filename: '${{ env.PRODUCTS_PATH }}/${{ env.IDENTIFIER }}_${{ env.REVISION }}.zip'
          exclusions: '*.def *.exp *.lib *.map *.o *.res *Unstripped* *.ignore'
```

**Comment by marceltaeumel** [comment]
Ah, I just saw the note that this works only in bash. Well, all Windows environments have a git bash. Would be nice if you one could run that action within that shell. 😃

**Comment by TheDoctor0** [comment]
Unfortunately, git bash is not a default Windows shell. 
Currently, it's just not possible to run both shell-based and Docker-based GitHub Action on Windows.

**Comment by marceltaeumel** [comment]
Okay. Well, in this case, it might be enough to just make the "entrypoint.sh" compatible with "bash" and not run "sh" from within the bash shell:

```
runs:
  ...
  steps:
    - shell: bash
      env:
        ...
      run: ${{ github.action_path }}/entrypoint.sh
```

At least I experienced similar path problems with running a command in a Cygwin shell from within the Windows PowerShell in a workflow.
