### ISSUE TITLE
File changed as we read it tar issue

### ISSUE THREAD

**Issue by dtcMLOps** [TheDoctor0/zip-release#31]
Hi @TheDoctor0,

Greetings.

I am getting an error when trying to compress a directory using the type `tar`. It seems when building the file it includes the `file.tar.gz` file during the process (that is being created in the same directory).

```bash
Run thedoctor0/zip-release@0.6.2
Run $GITHUB_ACTION_PATH/entrypoint.sh

📦 Creating tar archive...
./
./mymodule
./README.md
tar: .: file changed as we read it

⛔ Unable to create tar archive.
Error: Process completed with exit code [1]...
```

## Parameters
```yml
- name: Archive Release tar
  uses: thedoctor0/zip-release@0.6.2
  with:
    type: "tar"
    filename: "${{ github.event.repository.name }}-mypkg-v${{ needs.versioning.outputs.sem_version }}.tar.gz"
    directory: src/mymodule
    exclusions: "${{ github.event.repository.name }}-mypkg-v${{ needs.versioning.outputs.sem_version }}.tar.gz"
```

## Related post
- https://www.xmodulo.com/fix-tar-command-error.html
