### ISSUE TITLE
On Windows, got error INPUT_CUSTOM: unbound variable

### ISSUE THREAD

**Issue by thohng** [TheDoctor0/zip-release#35]
Got error on Windows: bash.EXE and unbound variable

- just got since commit: 7a1d901e34dbcfed63390cdb3a66ef4dffb50a4d
- action: `thedoctor0/zip-release@main`
- version: `main`

### Error:

```
📦 Creating zip archive...
D:\a\_actions\thedoctor0\zip-release\main/entrypoint.sh: line 19: INPUT_CUSTOM: unbound variable
Error: Process completed with exit code 1.
```

### Workaround
Add empty variable INPUT_CUSTOM on step or action

```
- name: Archive Release
  uses: thedoctor0/zip-release@main
  with:
    type: 'zip'
    filename: 'release.zip'
    exclusions: '*.git* /*node_modules/* .editorconfig'
  env:
    INPUT_CUSTOM: ""
```
