### ISSUE TITLE
Broken pipeline on update to v0.7.0,  `INPUT_CUSTOM: unbound variable`

### ISSUE THREAD

**Issue by Steve-Fry** [TheDoctor0/zip-release#36]
Evening,

An error I encountered today on update from 0.6.2 to 0.7. 

I'm running runner version `'2.300.0'` 
and 
```
Operating System
  Distribution: Amazon Linux
  Architecture: x86_64
```

The job step was fairly vanilla
```
    - name: Compress win10-x64 Build
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        path: src/myProject/bin/Release/net7.0/win10-x64/publish
        filename: 'Release_win10-x64.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
```

The failing log entry was
``` 
Run thedoctor0/zip-release@0.7.0
  with:
    type: zip
    path: src/myProject/bin/Release/net7.0/win10-x64/publish
    filename: Release_win10-x64.zip
    exclusions: *.git* /*node_modules/* .editorconfig
    directory: .
  env:
    DOTNET_ROOT: /usr/share/dotnet
Run $GITHUB_ACTION_PATH/entrypoint.sh
  $GITHUB_ACTION_PATH/entrypoint.sh
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DOTNET_ROOT: /usr/share/dotnet
    INPUT_FILENAME: Release_win10-x64.zip
    INPUT_PATH: src/myProject/bin/Release/net7.0/win10-x64/publish
    INPUT_DIRECTORY: .
    INPUT_EXCLUSIONS: *.git* /*node_modules/* .editorconfig
    INPUT_RECURSIVE_EXCLUSIONS: 
    INPUT_TYPE: zip

📦 Creating zip archive...
/opt/actions-runner/_work/_actions/thedoctor0/zip-release/0.7.0/entrypoint.sh: line 42 INPUT_CUSTOM: unbound variable
Error: Process completed with exit code 1.
```

I have not dabbled with actions, but by convention I see that unlike the other inputs, CUSTOM_INPUT isn't defined at 
https://github.com/TheDoctor0/zip-release/blob/d81722b768497cc1811c307cc7057ced9c25bf60/action.yml#L40-L47

Many thanks!
