### ISSUE TITLE
Have the extension be added automatically based on the type.

### ISSUE THREAD

**Issue by mcourteaux** [TheDoctor0/zip-release#38]
Right now, I have this YAML, which requires me to define both the `archive_type` and the `archive_extension`:
```yaml
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, windows-latest, macos-latest]
        include:
          - os: ubuntu-22.04
            outputsuffix: ubuntu-2204
            archive_type: tar
            archive_extension: tar.gz
          - os: ubuntu-20.04
            outputsuffix: ubuntu-2004
            archive_type: tar
            archive_extension: tar.gz
          - os: ubuntu-18.04
            outputsuffix: ubuntu-1804
            archive_type: tar
            archive_extension: tar.gz
          - os: macos-latest
            outputsuffix: mac
            archive_type: tar
            archive_extension: tar.gz
          - os: windows-latest
            outputsuffix: win
            archive_type: zip
            archive_extension: zip


    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: ${{matrix.archive_type}}
        filename: ${{github.workspace}}/build/lens_reproject_x64-avx2_${{matrix.outputsuffix}}.${{matrix.archive_extension}}
        directory: ${{github.workspace}}/build
```

Which is arguably a little cumbersome. Alternatively, you could also support "tar.gz" as a type instead of "tar". This way, we can reuse the variable.
