### ISSUE TITLE
problem generating zip from different branches for release

### ISSUE THREAD

**Issue by vindocel** [TheDoctor0/zip-release#39]
I'm trying to create a zip file for each branch I have to make a new release,
my code
```YAML
name: create archive
on:
  push:
    paths:
      - '**.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Get next version
        uses: reecetech/version-increment@2022.10.3
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Archive 1.19.3 Branch Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.19 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.19'

      - name: Zip 1.19 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Archive 1.18 Branch Release
        uses: actions/checkout@v2
        with:
          ref: '1.18'

      - name: Zip 1.18 Branch
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.version.outputs.version }}"
          name: "Dark Everywhere ${{ steps.version.outputs.version }}🌙"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```
the problem is that every time the new release is released only the last zip file is kept

`Dark_Everywhere_1.18.zip`

but he was supposed to go up to 3
I tried using the dependency

`ncipollo/release-action@v1`
and the
`marvinpinto/action-automatic-releases@latest`

but both give the same problem, which made me come to the conclusion that the problem may be that each zip that is generated is being subscribed on top of the other, then when the release is posted there is only the last file that was subscribed, you know how can i solve this problem?
