### ISSUE TITLE
Zipping nested folders

### ISSUE THREAD

**Issue by vodemn** [TheDoctor0/zip-release#42]
Hello! After executing the actions below
```
      - name: Zip merged_native_libs folder
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          directory: 'build/app/intermediates/merged_native_libs/prodRelease/out/lib/'
          filename: 'merged_native_libs.zip'

      - name: Upload merged_native_libs to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: merged_native_libs
          path: build/app/intermediates/merged_native_libs/prodRelease/out/lib/merged_native_libs.zip
```

I get the zipped folder with the following structure:
```
.
└── build/
    └── app/
        └── intermediates/
            └── merged_native_libs/
                └── prodRelease/
                    └── out/
                        └── lib/
                            └── <desired folders>
```

How can I get a zip with only `<desired folders>`?
