### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Andet-x** [TheDoctor0/zip-release#54]
![image](https://github.com/user-attachments/assets/1b92774d-30cc-49c2-9d0e-ff7a42bad6b0)
```
name: autorelise dev-build
on:
  push:
    tags:
      - "dev*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Andet-x** [comment]
yes I need almost all the files, when I added an exception (one directory) there was the same error

**Comment by Andet-x** [comment]
my project is very small

**Comment by TheDoctor0** [comment]
I would suggest following the recommendation and using:
```
name: autorelise dev-build
on:
  push:
    tags:
      - "dev*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          custom: '-i .'
          command: 'ls -la'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
```
The `ls -la` command will also list files before zipping, to see if there are any.

**Comment by Andet-x** [comment]
`	zip warning: zip file empty`

**Comment by Andet-x** [comment]
my repository is private, this may affect the results ?

**Comment by Andet-x** [comment]
```
name: autorelise dev-build
on:
  push:
    tags:
      - "dev*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: /.github/workflows/
          custom: '-i .'
          command: 'ls -la'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          ```
