### ISSUE TITLE
how to get tar or tar.gz compressed files for linux environment

### ISSUE THREAD

**Issue by PurnaChandraPanda** [TheDoctor0/zip-release#7]
I could get zip generated by using the following in .yml:

```
      - name: Zip Release
        ## You may pin to the exact commit or the version.
        # uses: TheDoctor0/zip-release@a1afcab9c664c9976ac398fa831eac67bed1eb0e
        uses: TheDoctor0/zip-release@0.4.1
        with:
          # Filename for archive
          filename: MyApp.zip
          # Base path for archive files
          path: ./package/
          # Working directory before zipping
          directory: .
          # List of excluded files / directories
          #exclusions: .
          # Tool to use for archiving
          type: zip
```

What all should I tweak for tar or tar.gz? If you have any example on tar side, please share it.
