### ISSUE TITLE
Zip file location

### ISSUE THREAD

**Issue by xuvvy** [TheDoctor0/zip-release#8]
Where is the created archive stored? Is there any possibility to attach it as an asset to a release?

**Comment by DearRude** [comment]
Same question...

**Comment by TheDoctor0** [comment]
Well, it's stored in a root directory if you use the default `release.zip` filenames - yes, you can use the path here.
To attach it to a release I personally use a combination of my `zip-release` action and:
```
- name: Upload Release
    uses: ncipollo/release-action@v1
    with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
```
